import { Option } from "@/models/Option";

const novelCategories: Option[] = [
  { title: 'Action', value: 'action' },
  { title: 'Adult', value: 'adult' },
  { title: 'Adventure', value: 'adventure' },
  { title: 'Comedy', value: 'comedy' },
  { title: 'Drama', value: 'drama' },
  { title: 'Ecchi', value: 'ecchi' },
  { title: 'Fantasy', value: 'fantasy' },
  { title: 'Gender Bender', value: 'gender-bender' },
  { title: 'Harem', value: 'harem' },
  { title: 'Historical', value: 'historical' },
  { title: 'Horror', value: 'horror' },
  { title: 'Josei', value: 'josei' },
  { title: 'Martial Arts', value: 'martial-arts' },
  { title: 'Mature', value: 'mature' },
  { title: 'Mecha', value: 'mecha' },
  { title: 'Mystery', value: 'mystery' },
  { title: 'Psychological', value: 'psychological' },
  { title: 'Romance', value: 'romance' },
  { title: 'School Life', value: 'school-life' },
  { title: 'Sci-fi', value: 'sci-fi' },
  { title: 'Seinen', value: 'seinen' },
  { title: 'Shoujo', value: 'shoujo' },
  { title: 'Shoujo Ai', value: 'shoujo-ai' },
  { title: 'Shounen', value: 'shounen' },
  { title: 'Shounen Ai', value: 'shounen-ai' },
  { title: 'Slice of Life', value: 'slice-of-life' },
  { title: 'Smut', value: 'smut' },
  { title: 'Sports', value: 'sports' },
  { title: 'Supernatural', value: 'supernatural' },
  { title: 'Tragedy', value: 'tragedy' },
  { title: 'Wuxia', value: 'wuxia' },
  { title: 'Xianxia', value: 'xianxia' },
  { title: 'Xuanhuan', value: 'xuanhuan' },
  { title: 'Yaoi', value: 'yaoi' },
  { title: 'Yuri', value: 'yuri' },
];

export default novelCategories;
